# This is a basic workflow to help you get started with Actions

name: CD Form PA

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      
    - name: deploy-gh-pages
      run: |
        # Move artifacts to a temporary location
        mv build /tmp/gh-pages
        # Hard reset to master to avoid conflicts.
        # Then, switch branch to gh-pages
        git reset --hard origin/master
        git clean -f -d
        git checkout gh-pages
        # Set the shopt dotglob bit to copy hidden files and directories
        shopt -s dotglob
        cp -a /tmp/gh-pages/* .
        git config --global user.email no-reply@teamdigitale.governo.it
        git config --global user.name "Deploy Bot"
        # Proceed only if there are changes to commit
        if [[ $(git status -s | wc -l | awk '{print $1}') -gt 0 ]]; then
          git add .
          git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}"
          git push origin gh-pages
        fi
