# This is a basic workflow to help you get started with Actions

name: Form PA CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy-gh-pages
    - run: |
        rm -rf gh-pages
        mv build gh-pages
        echo "formpa.developers.italia.it" > gh-pages/CNAME
        git config --global user.email no-reply@teamdigitale.governo.it
        git config --global user.name "Deploy Bot"
        if [[ $(git status -s | wc -l | awk '{print $1}') -gt 0 ]]; then
          git add gh-pages
          git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1} [ci skip]"
          git push origin $CIRCLE_BRANCH
        fi
